version: "3.7"
services:
  backend:
      build: .
      ports:
        - "8080:8080"
      environment: 
        - DB_PORT=3306
        - BACKEND_PORT=8080
        - DB_USER=95grad
        - DB_PASSOWRD=95grad_public
        - DB_NAME=95ers
        - JWT_SECRET=jwt_public
  mariadb:
    image: mariadb:10.3
    volumes: 
      - mariadbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 95_public_password
      MYSQL_DATABASE: 95ers
      MYSQL_USER: 95grad
      MYSQL_PASSWORD: 95grad_public
    ports:
      - "3306:3306"
    restart: on-failure

volumes: 
  mariadbdata:
    driver: local
  # commented for now, will uncomment late.
  # webserver:
  #   image: nginx:alpine
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./.nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf